[Compiler]
name    = "g++-mingw"
command = "g++"
cargs   = "-std=c++17 -O2 -flto -ffunction-sections -fdata-sections -fno-rtti -fno-exceptions -fvisibility=hidden -fvisibility-inlines-hidden -I. -Iinclude -Iwfx -c"
largs   = "-shared -flto -Wl,--gc-sections -Wl,--strip-all"
